Проверочное задание 2 урок
DariaJoy/JS pull request #2
Opened 2021-03-30 14:09 UTC by DariaJoy

2021-04-02 15:55 UTC, Om1X requested changes

2021-04-02 15:55 UTC, Om1X commented on lesson2Dzhagaryan.js
> +            break;
Функция должна возвращать результат посчитанный а не ссылки на другие функции

2021-04-03 15:50 UTC, DariaJoy commented on lesson2Dzhagaryan.js
> +            break;
исправила, доже теперь можно в алерте посмотреть результат : 
function mathOperation(arg1, arg2, operation) {
    switch (operation) {
        case addition:
            return arg1 + arg2;
        case subtraction:
            return arg1 - arg2;
        case division:
            return arg1 / arg2;
        case multiplication:
            return arg1 * arg2;
    }
}

alert(mathOperation(a, b, addition));
alert(mathOperation(a, b, subtraction));
alert(mathOperation(a, b, division));
alert(mathOperation(a, b, multiplication));

2021-04-03 16:37 UTC, merged

2021-04-13 14:20 UTC, Om1X commented on lesson2Dzhagaryan.js
> +            break;
здесь нужно было просто вызывать функции `return multiplication();`