Js5 lesson
DariaJoy/JS pull request #5
Opened 2021-04-13 16:26 UTC by DariaJoy

2021-04-21 01:11 UTC, Om1X approved these changes

2021-04-21 16:37 UTC, Om1X requested changes
Останется починить подсчет количества товара.

2021-04-21 16:37 UTC, Om1X commented on lesson6Dzhagaryan.js
> +                <button class="btnAddToCart" data-itemId="${item.itemId}">Добавить в корзину</button>
дата атрибут нужно писать так `data-item-id` это и будет `dataset.itemId`

2021-04-22 10:00 UTC, DariaJoy commented on lesson6Dzhagaryan.js
> +                <button class="btnAddToCart" data-itemId="${item.itemId}">Добавить в корзину</button>
Спасибо, про  дата атрибут нужно мне отдельно почитать, никогда его не использовала в верстке

2021-04-22 10:48 UTC, merged